# Generated by Django 5.2.1 on 2025-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='TODO', max_length=10),
        ),
    ]
